### ISSUE TITLE
Serial number not included

### ISSUE THREAD

**Issue by louatbodc** [rdawg-pidinst/schema#5]
Serial number should be at least be recommended as a sub-type to manufacturer. It's key information about an instrument instance.

**Comment by RKrahl** [comment]
It's redundant with AlternateIdentifier.

**Comment by louatbodc** [comment]
It is possible for two different manufacturers to use the same serial number (I've even known the same manufacturer to use the same serial numbers for two different models, especially when using serial numbers like 1,2,3 etc.). I wonder if this makes it more of a property of a manufacturer rather than an alternative identifier?

**Comment by RKrahl** [comment]
Obviously, identifiers are less useful if they are not unique. Every identifier is only unique within its scope at best. For `AlternateIdentifier`, we have `alternateIdentifierType` to define and narrow down the scope. It is in the nature of things that the problem of uniqueness and well-definedness is worse for less formalized identifiers such as inventory numbers or serial numbers then it is for well established PIDs. And it will be mostly those less formalized identifiers that will be relevant for alternate identifiers.

So this problem exist, no doubt about that. But I can't see how the name of the property will make a difference here. Whether we store the serial number as `AlternateIdentifier` or in a dedicated property `serialNumber`, the problem of lack of uniqueness in serial numbers stays the same.

But we should avoid redundancy in the schema. For any given piece of information, there should ideally be only one property in the schema to store it. We already have `AlternateIdentifier`. This property is well suited to store serial numbers. `AlternateIdentifier` will not become obsolete if we add `serialNumber`, because there are plenty of other types of alternate identifiers that we need to accommodate. If we add `serailNumber`, we get two different places where a serial number could be stored. As a result some providers of the PIDINST will use the one property, others will use the other. Consumers of the PID will be forced to look in both places. The mess will be even worse.

**Comment by RKrahl** [comment]
@louatbodc: after the amendment to `AlternateIdentifier`, are you happy to close?

**Comment by huberrob** [comment]
Please do not close this issue, it is closely related to #15 and should be discussed in context.
I strongly recommend to include serial numbers within the schema.

**Comment by RKrahl** [comment]
I believe we have a consensus by now that the serial number should be included as `AlternateIdentifier`.  I suggest to close this one. Note that #24 is still open.

**Comment by RKrahl** [comment]
Close as discussed in to meeting today.
